// Generated by CoffeeScript 1.12.3
(function() {
  var R, invariant,
    slice = [].slice;

  invariant = function(cond, msg) {
    var error;
    if (!cond) {
      error = new Error(cond);
      error.framesToPop = 1;
      throw error;
    }
  };

  R = function() {
    var component, i, len, path, route, transformer, transformers;
    path = arguments[0], component = arguments[1], transformers = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    route = {
      path: path,
      component: component
    };
    for (i = 0, len = transformers.length; i < len; i++) {
      transformer = transformers[i];
      route = transformer(route);
    }
    return route;
  };

  R.child = function(childRoute) {
    return function(r) {
      if (!Array.isArray(r.childRoutes)) {
        r.childRoutes = [];
      }
      r.childRoutes.push(childRoute);
      return r;
    };
  };

  R.index = function(component) {
    return function(r) {
      invariant(!('indexRoute' in r), 'indexRoute already added');
      r.indexRoute = component;
      return r;
    };
  };

  module.exports = R;

}).call(this);
