// Generated by CoffeeScript 1.12.3
(function() {
  var R, createElement, ensureNotIn,
    slice = [].slice;

  createElement = require('react').createElement;

  ensureNotIn = function(field, obj, msg) {
    var error;
    if (field in obj) {
      error = new Error(msg + ". Found " + field + " in route");
      error.framesToPop = 1;
      throw error;
    }
  };

  R = function() {
    var component, i, len, path, route, transformer, transformers;
    path = arguments[0], component = arguments[1], transformers = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    route = {
      path: path,
      component: component
    };
    for (i = 0, len = transformers.length; i < len; i++) {
      transformer = transformers[i];
      route = transformer(route);
    }
    return route;
  };

  R.child = function(childRoute) {
    return function(route) {
      if (!Array.isArray(route.childRoutes)) {
        route.childRoutes = [];
      }
      route.childRoutes.push(childRoute);
      return route;
    };
  };

  R.index = function(component) {
    return function(route) {
      ensureNotIn('indexRoute', route, 'index can only be used once');
      ensureNotIn('getIndexRoute', route, 'Unexpected error');
      route.indexRoute = {
        component: component
      };
      return route;
    };
  };

  module.exports = R;

}).call(this);
